sudo: false
language: bash
os:
  - linux
env:
  global:
    - HELTECCOMMIT=348f16525b3280792c1289ee015666774251afd5
    - AUNITCOMMIT=25637e47295b0a4c0166de631780ebfa0f057668
  matrix:
    - HARDWARE=esp8266com/esp8266 \
      COREGIT=https://github.com/esp8266/Arduino.git \
      CORECOMMIT=d8a7a34caff4feb3d3e42d94b5a159df32807e4a \
      BOARD='--board esp8266com:esp8266:nodemcuv2  --pref custom_xtal=nodemcuv2_80 --pref custom_eesz=nodemcuv2_4M1M'
    - HARDWARE=espressif/esp32 \
      COREGIT=https://github.com/espressif/arduino-esp32.git \
      CORECOMMIT=e5ea089a7fd5cc8a96d68aae64dc3b4dcef2315e \
      BOARD='--board espressif:esp32:heltec_wifi_kit_32 --pref custom_FlashFreq=heltec_wifi_kit_32_80'

install:
  - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_1.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :1 -ac -screen 0 1280x1024x16
  - mkdir -p $HOME/arduino_ide; cd $HOME/arduino_ide
  - curl -L http://downloads.arduino.cc/arduino-1.8.7-linux64.tar.xz | tar xJ --strip 1
  - export PATH="$HOME/arduino_ide:$PATH"
  - cd $HOME/arduino_ide/hardware
  - mkdir -p $HARDWARE; cd $HARDWARE
  - git init; git fetch $COREGIT; git checkout $CORECOMMIT; git submodule update --init
  - cd tools; python get.py
  - mkdir -p $HOME/Arduino/libraries; cd $HOME/Arduino/libraries
  - curl -L https://github.com/Heltec-Aaron-Lee/WiFi_Kit_series/archive/$HELTECCOMMIT.tar.gz | tar xz WiFi_Kit_series-$HELTECCOMMIT/esp32/libraries/LoRa --strip-components=3
  - curl -L https://github.com/bxparks/AUnit/archive/$AUNITCOMMIT.tar.gz | tar xz; mv AUnit-$AUNITCOMMIT AUnit

before_script:
  - cp -r $TRAVIS_BUILD_DIR $HOME/Arduino/libraries/esp8266ndn
  - export DISPLAY=:1.0
  - arduino $BOARD --save-prefs
  - arduino --get-pref

script:
  - |
     NFAIL=0
     for SKETCH in $(find $TRAVIS_BUILD_DIR -name '*.ino'); do
       echo
       echo
       echo -e '\033[0;36m'Building $SKETCH '\033[0m'
       echo
       arduino --verify $SKETCH || NFAIL=$((NFAIL+1))
     done
     [[ $NFAIL -eq 0 ]]
